CREATE TABLE IF NOT EXISTS loans (
  id INT PRIMARY KEY AUTO_INCREMENT,
  loan_reference VARCHAR(20) NOT NULL UNIQUE,
  client_id INT NOT NULL,
  amount DECIMAL(10, 2) NOT NULL,
  purpose VARCHAR(255) NOT NULL,
  duration INT NOT NULL COMMENT 'Loan duration in months',
  interest_rate DECIMAL(5, 2) NOT NULL,
  monthly_payment DECIMAL(10, 2) NOT NULL,
  status ENUM('approved', 'rejected', 'pending') NOT NULL,
  decision_reason TEXT NOT NULL,
  risk_score DECIMAL(6,4) DEFAULT NULL,
  monthly_income DECIMAL(10, 2) NOT NULL,
  employment_status ENUM('employed', 'self-employed', 'unemployed', 'retired') NOT NULL,
  existing_loans INT NOT NULL DEFAULT 0,
  statement_path VARCHAR(255) DEFAULT NULL,
  application_date TIMESTAMP NOT NULL,
  decision_date TIMESTAMP NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (client_id) REFERENCES clients(id),
  INDEX idx_loan_reference (loan_reference),
  INDEX idx_client_id (client_id),
  INDEX idx_status (status),
  INDEX idx_application_date (application_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci; 
